//google fetching
export const ITERATE_RESULT_AND_DETAILS_INDICES = 'ITERATE_RESULT_AND_DETAILS_INDICES';
export const SET_RESULTS_OBJECT = 'SET_RESULTS_OBJECT';
export const SET_DETAILS_OBJECT = 'SET_DETAILS_OBJECT';
export const SET_DETAILS_DATA = 'SET_DETAILS_DATA';
export const SET_IMAGE_URLS = 'SET_IMAGE_URLS';
export const RESET_RESULTS_INDEX_AND_CURRENT_DETAILS_INDEX = 'RESET_RESULTS_INDEX_AND_CURRENT_DETAILS_INDEX';
export const RESET_CURRENT_DETAILS_INDEX = 'RESET_CURRENT_DETAILS_INDEX';
export const REMOVE_RESULTS_OBJECT = 'REMOVE_RESULTS_OBJECT';
export const ITERATE_CURRENT_DETAILS_INDEX = 'ITERATE_CURRENT_DETAILS_INDEX';
export const RAN_OUT_OF_RESULTS = 'RAN_OUT_OF_RESULTS';

//settings
export const SET_THEME = 'SET_THEME';
export const SET_RADIUS = 'SET_RADIUS';
export const SET_PRICE = 'SET_PRICE';
export const SET_LOCATION = 'SET_LOCATION';
export const SHUFFLE_CURRENT_THEME = 'SHUFFLE_CURRENT_THEME';
export const ITERATE_THEME_INDEX = 'ITERATE_THEME_INDEX';

//hacks
export const RESET_STACK = 'RESET_STACK';
