//navigation
export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD';
export const NAVIGATION_BACK = 'NAVIGATION_BACK';
export const MAKE_TRANSITION_VERTICAL = 'MAKE_TRANSITION_VERTICAL';
export const MAKE_TRANSITION_HORIZONTAL = 'MAKE_TRANSITION_HORIZONTAL';
export const PUSH = 'PUSH';
export const POP = 'POP';
export const ITERATE_RESULT_INDEX = 'ITERATE_RESULT_INDEX';
