//navigation
export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD';
export const NAVIGATION_BACK = 'NAVIGATION_BACK';
export const MAKE_TRANSITION_VERTICAL = 'MAKE_TRANSITION_VERTICAL';
export const MAKE_TRANSITION_HORIZONTAL = 'MAKE_TRANSITION_HORIZONTAL';
export const PUSH = 'PUSH';
export const POP = 'POP';

//google fetching
export const ITERATE_RESULT_INDEX = 'ITERATE_RESULT_INDEX';
export const SET_RESULTS_JSON = 'SET_RESULTS_JSON';
export const SET_DETAILS_JSON = 'SET_DETAILS_JSON';
export const SET_DETAILS_DATA = 'SET_DETAILS_DATA';
export const SET_IMAGE_URLS = 'SET_IMAGE_URLS';
export const SET_RESULTS_OBJECT = 'SET_RESULTS_OBJECT';
export const SET_THEME = 'SET_THEME';
export const RESET_INDICES = 'RESET_INDICES';
export const SET_RADIUS = 'SET_RADIUS';
export const SET_PRICE = 'SET_PRICE';
